### ISSUE TITLE
Typo miss

### ISSUE THREAD

**Issue by xoxwgys56** [xdfc1745/xdfc1745#1]
Hello I read your profile. nice and simple. but there is a typo miss.

> I am Gayoung Kim who is interested NLP from South Korea. If you want to contact me, please `sentd` me a mail.

You should correct word `sentd` to `send`. I suppose to.  
Also if you do not mind I suggest more readable text below.

> I am Ga-young Kim who interested in **NLP**. You can contact me using [email](xdfc1745@gmail.com)

---

Even more, You can iterate your contact list like below

> You can contact me using email, linked-in and facebook.

Thanks.

**Comment by xdfc1745** [comment]
okay thanks :)

**Comment by xoxwgys56** [comment]
@xdfc1745 

Thanks for accept my suggestion.  

But I guess you should explicitly specifying you email like below.  

```plain
- [email](your email address)
- [gmail](also your email)
- [email address](shortcut to send email to yours)
```

Thanks!
